### ISSUE TITLE
Silently failing import

### ISSUE THREAD

**Issue by Jbudone** [typesense/typesense-php#21]
Using scout:import my imports are silently failing. I can add the following to Typesense.php to see the error
```
    public function importDocuments(Collection $collectionIndex, $documents, string $action = 'upsert'): void
    {
        $results = $collectionIndex->getDocuments()
                        ->import($documents, ['action' => $action]);

        foreach ($results as &$result)
        {
            if ($result['success'] == false) {
                echo "Could not importDocuments: " . $result['error'] . "\n";
            }
        }
    }
```

However this means looping over all results to check, and no access to $this->apiCall. There's probably a better way to do this for error logging

```
Could not importDocuments: Document's `id` field should be a string.
Could not importDocuments: Document's `id` field should be a string.
Could not importDocuments: Document's `id` field should be a string.
Could not importDocuments: Document's `id` field should be a string.
...
```

**Comment by AbdullahFaqeir** [comment]
Hello @Jbudone 

The part of this issue inside the client itself has been fixed, as the import method is currently returning the array of results corresponding to each document, this issue shall be fixed in the scout-driver part, if you care to open an issue on the driver repo.

This issue will be closed.
